@ECHO OFF

SETLOCAL EnableDelayedExpansion

SET APPNAME=WindowSpy
SET APPDESCRIPTION=Window Spy
SET APPFILENAME=%APPNAME%.ahk
SET EXEFILENAME=%APPNAME%.exe
SET ICONFILENAME=spy_BNl_icon.ico

CALL ..\BuildAHK.cmd "%~n0" "%APPNAME%" "%APPDESCRIPTION%" "%APPFILENAME%" "%EXEFILENAME%" "%ICONFILENAME%"
