@ECHO OFF

SETLOCAL EnableDelayedExpansion

SET APPNAME=MyHotKeys
SET APPDESCRIPTION=My Custom Hotkeys
SET APPFILENAME=%APPNAME%.ahk
SET EXEFILENAME=%APPNAME%.exe
SET ICONFILENAME=%APPNAME%.ico

CALL ..\BuildAHK.cmd "%~n0" "%APPNAME%" "%APPDESCRIPTION%" "%APPFILENAME%" "%EXEFILENAME%" "%ICONFILENAME%"
