@ECHO OFF

SETLOCAL EnableDelayedExpansion

SET SCRIPTPATH=%~dp0
SET SCRIPTNAME=%~n0
SET SCRIPTFULLFILENAME=%~dpnx0

FOR %%* IN (.) DO SET CURRENTDIR=%%~dpn*
FOR %%* IN (.) DO SET CURRENTDIRNAME=%%~n*

SET CONFIG_FILENAME=.%SCRIPTNAME%.config.toml

SET ALLOWMULTICOMMANDEXECUTION=N

SET HELP=N
SET DEBUG=N
SET DRYRUN=N
SET SHOWCOMMAND=N

SET ARGPOS=0
SET KNOWNCOMMANDCOUNT=0
SET KNOWNALIASCOUNT=0
SET COMMANDCOUNT=0

REM                   NAME     DESCRIPTION
CALL :DEFINECOMMAND   clone    "Clone a Repo"
CALL :DEFINECOMMAND   baseurl  "Set the Base URL for repos in this folder"
CALL :DEFINECOMMAND   status   "Show current status information"
CALL :DEFINECOMMAND   branch   "Show current branch"
CALL :DEFINECOMMAND   unstage  "Unstage a file already added"
CALL :DEFINECOMMAND   reset    "Reset (Undo) changes to a file"
CALL :DEFINECOMMAND   remstat  "Show Remote Branch Status"
CALL :DEFINECOMMAND   config   "Show all Config (with scopes / files)"
CALL :DEFINECOMMAND   clean    "Clean all untracked files" 

CALL :DEFINEALIAS cfg config

REM ** TODO: Set these as appropriate
SET MAXCOMMANDNAMEDISPLAYLENGTH=8
SET MAXOPTIONNAMEDISPLAYLENGTH=8

:PARSE
IF "%~1" === "" GOTO :VALIDATE
IF /I "%~1" == "/?"  SET HELP=Y&&SHIFT&&GOTO :PARSE
IF /I "%~1" == "-?"  SET HELP=Y&&SHIFT&&GOTO :PARSE
IF /I "%~1" == "/X"  SET DEBUG=Y&&SHIFT&&GOTO :PARSE
IF /I "%~1" == "-X"  SET DEBUG=Y&&SHIFT&&GOTO :PARSE
IF /I "%~1" == "/Z"  SET DRYRUN=Y&&SHIFT&&GOTO :PARSE
IF /I "%~1" == "-Z"  SET DRYRUN=Y&&SHIFT&&GOTO :PARSE

IF /I "%~1" == "/SC" SET SHOWCOMMAND=Y&&SHIFT&&GOTO :PARSE
IF /I "%~1" == "-SC" SET SHOWCOMMAND=Y&&SHIFT&&GOTO :PARSE


SET /A ARGPOS+=1
IF %ARGPOS% GTR 1 (
   IF "%ALLOWMULTICOMMANDEXECUTION%" == "N" GOTO :PARSEERROR
)

CALL :LOCATECOMMANDEXACT "%~1"
IF "%FOUND%" == "Y" SHIFT && GOTO :PARSE

CALL :LOCATECOMMANDPARTIAL "%~1"
IF "%FOUND%" == "Y" SHIFT && GOTO :PARSE

IF "%ALLOWMULTICOMMANDEXECUTION%" == "N" GOTO :PARSEERROR

CALL :LOCATECOMMANDSCOMBINED "%~1"
IF "%FOUND%" == "Y" SHIFT && GOTO :PARSE

:PARSEERROR
CALL :USAGE
ECHO.
CALL :ERROR Unknown argument at position: %ARGPOS% - %~1
GOTO :EOF


:VALIDATE
IF "%HELP%" == "Y"    CALL :USAGE && GOTO :EOF
IF "%DEBUG%" == "Y"   SET SHOWCOMMAND=Y
IF "%DRYRUN%" == "Y"  SET COMMANDPREFIX=@ECHO.

IF %COMMANDCOUNT% EQU 0 (
    CALL :USAGE
    ECHO.
    CALL :ERROR No command provided
    GOTO :EOF
)


SET COMMANDINDEX=0

:COMMANDEXECUTEPARSE
SET /A COMMANDINDEX+=1
SET EXECCOMMAND=!COMMAND[%COMMANDINDEX%]!
IF "%EXECCOMMAND%" == "" GOTO :EOF

REM *** Match a command
SET FOUND=

CALL :LOCATECOMMANDEXACT "%EXECCOMMAND%"
IF NOT "%FOUND%" == "" (
    CALL :COMMAND_!LABEL! %*
    GOTO :EOF
)

CALL :LOCATECOMMANDPARTIAL "%EXECCOMMAND%"
IF NOT "%FOUND%" == "" (
    CALL :COMMAND_!LABEL! %*
    GOTO :EOF
)

IF "%ALLOWMULTICOMMANDEXECUTION%" == "N" GOTO :COMMANDEXECUTEPARSE_ERROR

CALL :LOCATECOMMANDCOMBINED "%EXECCOMMAND%"

:COMMANDEXECUTEPARSE_ERROR
ECHO.
CALL :ERROR Command not found: %EXECCOMMAND%

IF %CANDIDATES% GTR 0 (
    ECHO.
    ECHO.Ambiguous Command:
    FOR /L %%F IN (1,1,%CANDIDATES%) DO (
        CALL :SETCOMMANDBYINDEX !CANDIDATE[%%F]!

        ECHO.!NAME! - !DESC!
    )
)

GOTO :EOF


:DEFINECOMMAND

SET /A KNOWNCOMMANDCOUNT+=1
SET KNOWNCOMMAND[%KNOWNCOMMANDCOUNT%].NAME=%~1
SET KNOWNCOMMAND[%KNOWNCOMMANDCOUNT%].LABEL=%~2
SET KNOWNCOMMAND[%KNOWNCOMMANDCOUNT%].DESC=%~3

GOTO :EOF


:DEFINEALIAS

SET /A KNOWNALIASCOUNT+=1
SET KNOWNALIAS[%KNOWNALIASCOUNT%].ALIAS=%~1
SET KNOWNALIAS[%KNOWNALIASCOUNT%].NAME=%~2

GOTO :EOF


:ERROR
ECHO.ERROR: %*

GOTO :EOF


:WARNING
ECHO.WARNING: %*

GOTO :EOF


:SETCOMMANDBYINDEX
SET NAME=!COMMAND[%~1].NAME!
SET LABEL=!COMMAND[%~1].LABEL!
SET DESC=!COMMAND[%~1].DESC!

GOTO :EOF


:LOCATECOMMANDEXACT
SET FOUND=

FOR /L %%F IN (1,1,%COMMANDCOUNT%) DO (
    CALL :SETCOMMANDBYINDEX %%F
    
    IF /I "%~1" == "!NAME!" (
        SET FOUND=%%F
        GOTO :EOF
    )
)

GOTO :EOF


:LOCATECOMMANDBEST
SET FOUND=

SET CANDIDATES=0

FOR /L %%F IN (1,1,%COMMANDCOUNT%) DO (
    CALL :SETCOMMANDBYINDEX %%F
    
    ECHO.!NAME!|FINDSTR "^%~1">NUL && SET /A CANDIDATES+=1 && SET "CANDIDATE[!CANDIDATES!]=%%F"
)

IF %CANDIDATES% EQU 0 (
    GOTO :EOF
)

IF %CANDIDATES% EQU 1 (
    SET FOUND=%CANDIDATE[1]%
    CALL :SETCOMMANDBYINDEX %CANDIDATE[1]%
    GOTO :EOF
)

GOTO :EOF


:USAGE
ECHO.%SCRIPTNAME% - GIT shortcuts
ECHO.
ECHO.Usage: %SCRIPTNAME% [command] { [args] } { [options] }
ECHO.
ECHO.Commands:
FOR /L %%F IN (1,1,%COMMANDCOUNT%) DO (
    CALL :SETCOMMANDBYINDEX %%F

    REM ECHO.!NAME! - !DESC!
    REM PRINTFORMAT   "{0,-%MAXCOMMANDNAMEDISPLAYLENGTH%} - {1}" "!NAME!" "!DESC!"
    PRINTFORMAT_R "{:<%MAXCOMMANDNAMEDISPLAYLENGTH%} - {}" "!NAME!" "!DESC!"
)
ECHO.
ECHO.Options:
PRINTFORMAT_R "{:<%MAXOPTIONNAMEDISPLAYLENGTH%} - {}" "/?" "Show Usage"
PRINTFORMAT_R "{:<%MAXOPTIONNAMEDISPLAYLENGTH%} - {}" "/X" "Activate Debug mode (Default: %DEBUG%)"
PRINTFORMAT_R "{:<%MAXOPTIONNAMEDISPLAYLENGTH%} - {}" "/Z" "Activate Dry Run mode (Default: %DRYRUN%)"
PRINTFORMAT_R "{:<%MAXOPTIONNAMEDISPLAYLENGTH%} - {}" "/SC" "Show Commands (Default: %SHOWCOMMAND%)"

GOTO :EOF


:EXECUTE_CLONE
CALL GetTOMLValue.cmd ".BaseUrl" -f %REPO_CONFIG_FILENAME%

SET SOURCE=%~2
IF /I "%SOURCE:~1,7%" == "http://" (
    ECHO.Using source : %SOURCE%
) ELSE IF /I "%SOURCE:~1,8%" == "https://" (
    ECHO.Using source : %SOURCE%
) ELSE (
    SET SOURCE=%TOMLVALUE%%SOURCE%
    ECHO.Using source %TOMLVALUE%%SOURCE%
)

@IF "%SHOWCOMMAND%" == "Y" @ECHO ON
%COMMANDPREFIX%git clone %SOURCE%
@IF "%SHOWCOMMAND%" == "Y" @ECHO OFF
GOTO :EOF


:EXECUTE_BASEURL
IF "%~2" == "" (
    CALL :ERROR Invalid Base URL
    GOTO :EOF
)

ECHO.BaseUrl = %~2> %REPO_CONFIG_FILENAME%
TYPE %REPO_CONFIG_FILENAME%

GOTO :EOF


:EXECUTE_STATUS
@IF "%SHOWCOMMAND%" == "Y" @ECHO ON
%COMMANDPREFIX%git status
@IF "%SHOWCOMMAND%" == "Y" @ECHO OFF

GOTO :EOF


:EXECUTE_BRANCH
@IF "%SHOWCOMMAND%" == "Y" @ECHO ON
%COMMANDPREFIX%git rev-parse --abbrev-ref HEAD
@IF "%SHOWCOMMAND%" == "Y" @ECHO OFF

GOTO :EOF


:EXECUTE_UNSTAGE
IF "%~2" == "" (
  CALL :ERROR Invalid filename to unstage
  GOTO :EOF
)

@IF "%SHOWCOMMAND%" == "Y" @ECHO ON
%COMMANDPREFIX%git reset HEAD "%~2"
@IF "%SHOWCOMMAND%" == "Y" @ECHO OFF

GOTO :EOF


:EXECUTE_RESET
IF "%~2" == "" (
  CALL :ERROR Invalid filename to reset
  GOTO :EOF
)

@IF "%SHOWCOMMAND%" == "Y" @ECHO ON
%COMMANDPREFIX%git checkout -- "%~2"
@IF "%SHOWCOMMAND%" == "Y" @ECHO OFF

GOTO :EOF


:EXECUTE_REMOTEBRANCHSTATUS
CALL BUILDUNIQUETEMPFILENAME "%SCRIPTNAME%.RemoteBranchStatus.tmp"
SET TEMPFILENAME=%UNIQUETEMPFILENAME%

@IF "%SHOWCOMMAND%" == "Y" @ECHO ON
%COMMANDPREFIX%git branch -r | grep -v HEAD > "%TEMPFILENAME%"
@IF "%SHOWCOMMAND%" == "Y" @ECHO OFF

FOR /F %%F IN (%TEMPFILENAME%) DO CALL :SHOWSTATUS "%%~F"

DEL /Q "%TEMPFILENAME%" >NUL

GOTO :EOF


:EXECUTE_SHOWSTATUS
@IF "%SHOWCOMMAND%" == "Y" @ECHO ON
%COMMANDPREFIX%git show --format="%%ci %%cr %%cn %%d" "%~1" | head -n 1
@IF "%SHOWCOMMAND%" == "Y" @ECHO OFF

GOTO :EOF


:EXECUTE_SHOWCONFIG
SET PARAM=--show-scope
IF /I "%~2" == "FILE"  SET PARAM=--show-origin
IF /I "%~2" == "FILES" SET PARAM=--show-origin

@IF "%SHOWCOMMAND%" == "Y" @ECHO ON
%COMMANDPREFIX%git config --list %PARAM%
@IF "%SHOWCOMMAND%" == "Y" @ECHO OFF

GOTO :EOF


:EXECUTE_CLEAN
REM https://stackoverflow.com/questions/61212/how-do-i-remove-local-untracked-files-from-the-current-git-working-tree

@IF "%SHOWCOMMAND%" == "Y" @ECHO ON
%COMMANDPREFIX%git clean -fdx
@IF "%SHOWCOMMAND%" == "Y" @ECHO OFF

GOTO :EOF
