@ECHO OFF

SETLOCAL

CALL "%~dp0\Aliases.cmd" INSTALL

:CUSTOM
SET CUSTOM_AUTORUN=%USERPROFILE%\MyAutorun.cmd
IF EXIST "%CUSTOM_AUTORUN%" (
  ECHO.Executing: %CUSTOM_AUTORUN%
  CALL "%CUSTOM_AUTORUN%"
)
