@ECHO OFF

IF "%~1" == "" (
    CALL :USAGE
    GOTO :EOF
)

CALL :BUILDUNIQUEFILENAME "%~1" "%~2"

GOTO :EOF


:USAGE
ECHO.%~n0 - Generate a unique temporary filename
ECHO.
ECHO.Usage:
ECHO.%~n0 [base-file-name] { [folder] }
GOTO :EOF


:ERROR
ECHO.ERROR: %~1
GOTO :EOF


:BUILDUNIQUEFILENAME
SET BUILDUNIQUEFILENAMEID=0
SET BUILDUNIQUEFILENAMEPART=%~n1
SET BUILDUNIQUEFILEEXTPART=%~x1
SET BUILDUNIQUEFILEFOLDER=%~2

IF "%BUILDUNIQUEFILEFOLDER%" == "" SET BUILDUNIQUEFILEFOLDER=%TEMP%


:BUILDUNIQUEFILENAME_LOOP
SET /A BUILDUNIQUEFILENAMEID+=1
SET UNIQUETEMPFILENAME=%BUILDUNIQUEFILEFOLDER%\%BUILDUNIQUEFILENAMEPART%.%BUILDUNIQUEFILENAMEID%%BUILDUNIQUEFILEEXTPART%

IF EXIST "%UNIQUETEMPFILENAME%" GOTO :BUILDUNIQUEFILENAME_LOOP

REM Claim it
TOUCH "%UNIQUETEMPFILENAME%"

REM Reset variables
SET BUILDUNIQUEFILENAMEID=
SET BUILDUNIQUEFILENAMEPART=
SET BUILDUNIQUEFILEEXTPART=
SET BUILDUNIQUEFILEFOLDER=

GOTO :EOF
