@ECHO OFF

SETLOCAL EnableDelayedExpansion

SET SCRIPTPATH=%~dp0
SET SCRIPTNAME=%~n0
SET SCRIPTFULLFILENAME=%~dpnx0

REM * %1  - filename
REM * %2  - backup method
REM * %3+ - backup method specific options

IF "%~1" == "" (
    CALL :USAGE
    GOTO :EOF
)
IF NOT EXIST "%~1" (
    CALL :ERROR File not found: %~1
    GOTO :EOF
)

IF /I "%~2" == "NUMBER" CALL :BACKUP_%~2 %~1 %~3 %~4

GOTO :EOF


:USAGE
:USAGE
ECHO.%SCRIPTNAME% - Create a backup copy of a file
ECHO.
ECHO.%SCRIPTNAME% [file-name] [backup-method] { [backup-method-options] }
ECHO.
ECHO.backup-method:
ECHO.   NUMBER { [max-copies:10] { [min-digits:2] } }
ECHO.

GOTO :EOF


:BACKUP_NUMBER
SET MAXCOPIES=%~2
SET MINDIGITS=%~3

IF "%MAXCOPIES%" == "" SET MAXCOPIES=10
IF "%MINDIGITS%" == "" SET MINDIGITS=2

SET /A TARGET=%MAXCOPIES% * 1
:BACKUP_NUMBER_LOOP
SET /A SOURCE=%TARGET% - 1

REM ECHO.SOURCE: %SOURCE%
REM ECHO.TARGET: %TARGET%

REM CALL :REPEAT 0 %MINDIGITS%
REM ECHO.REPEATTEXT=%REPEATTEXT%
REM 
REM SET SOURCEFMT=%REPEATTEXT%%SOURCE%
REM SET TARGETFMT=%REPEATTEXT%%TARGET%
REM 
REM CALL SET SOURCEFMT=%SOURCEFMT:~-%MINDIGITS%%
REM CALL SET TARGETFMT=%TARGETFMT:~-%MINDIGITS%%
REM ECHO.SOURCEFMT=%SOURCEFMT%
REM ECHO.TARGETFMT=%TARGETFMT%
REM 
REM GOTO :EOF

SET TMPFILE1=%~dpnx1.!SOURCE!
SET TMPFILE2=%~dpnx1.!TARGET!

IF %SOURCE% GTR 0 (

    IF EXIST "!TMPFILE1!" (
        CALL :MOVEFILE "!TMPFILE1!" "!TMPFILE2!"
    )
    
    SET /A TARGET=!TARGET! - 1
    
    GOTO :BACKUP_NUMBER_LOOP
)

SET TMPFILE1=%~dpnx1.%TARGET%
CALL :COPYFILE "%~1" "%TMPFILE1%"

GOTO :EOF


:REPEAT
SET REPEATTEXT=
FOR /L %%i IN (1,1,%~2) DO CALL set "REPEATTEXT=%%REPEATTEXT%%%~1"

GOTO :EOF


:COPYFILE
IF "%~1" == "" GOTO :EOF
IF "%~2" == "" GOTO :EOF

COPY /Y "%~1" "%~2" > NUL

GOTO :EOF


:MOVEFILE
IF "%~1" == "" GOTO :EOF
IF "%~2" == "" GOTO :EOF

MOVE /Y "%~1" "%~2" > NUL

GOTO :EOF


:DELETEFILE
IF "%~1" == "" GOTO :EOF

IF NOT EXIST "%~1" GOTO :EOF

DEL /Q "%~1" > NUL

GOTO :EOF
