@ECHO OFF

FOR /F "tokens=1-3 delims=/-" %%a IN ('ShowDateTime -f "%%Y-%%m-%%d"') DO (
    SET CURRENTDATETIME_YEAR=%%a
    SET CURRENTDATETIME_MONTH=%%b
    SET CURRENTDATETIME_DAY=%%c
)

FOR /F "tokens=1-4 delims=/:" %%a IN ('ShowDateTime -f "%%H:%%M:%%S:{fff}"') DO (
    SET CURRENTDATETIME_HOUR=%%a
    SET CURRENTDATETIME_MINUTE=%%b
    SET CURRENTDATETIME_SECOND=%%c
    SET CURRENTDATETIME_MILLISECOND=%%d
)

FOR /F "tokens=1-2 delims=/:" %%a IN ('ShowDateTime -f {jjj}:{q}') DO (
    SET CURRENTDATETIME_JULIANDAY=%%a
    SET CURRENTDATETIME_QUARTER=%%b
)

SET CURRENTDATETIME=%CURRENTDATETIME_YEAR%-%CURRENTDATETIME_MONTH%-%CURRENTDATETIME_DAY% %CURRENTDATETIME_HOUR%:%CURRENTDATETIME_MINUTE%:%CURRENTDATETIME_SECOND%.%CURRENTDATETIME_MILLISECOND%

IF /I "%~1" == "/X" (
    ECHO.CURRENTDATETIME=%CURRENTDATETIME%
    ECHO.
    ECHO.YEAR=%CURRENTDATETIME_YEAR%
    ECHO.MONTH=%CURRENTDATETIME_MONTH%
    ECHO.DAY=%CURRENTDATETIME_DAY%
    ECHO.HOUR=%CURRENTDATETIME_HOUR%
    ECHO.MINUTE=%CURRENTDATETIME_MINUTE%
    ECHO.SECOND=%CURRENTDATETIME_SECOND%
    ECHO.MILLISECOND=%CURRENTDATETIME_MILLISECOND%
    ECHO.JULIANDAY=%CURRENTDATETIME_JULIANDAY%
    ECHO.QUARTER=%CURRENTDATETIME_QUARTER%
)

