@ECHO OFF

FOR /F "tokens=1-3 delims=/-" %%a IN ('ShowDateTime -f yyyy-MM-dd') DO (
    SET CURRENTDATETIME_YEAR=%%a
    SET CURRENTDATETIME_MONTH=%%b
    SET CURRENTDATETIME_DAY=%%c
)

FOR /F "tokens=1-4 delims=/:" %%a IN ('ShowDateTime -f HH:mm:ss:000') DO (
    SET CURRENTDATETIME_HOUR=%%a
    SET CURRENTDATETIME_MINUTE=%%b
    SET CURRENTDATETIME_SECOND=%%c
    SET CURRENTDATETIME_MILLISECOND=%%d
)

SET CURRENTDATETIME=%CURRENTDATETIME_YEAR%-%CURRENTDATETIME_MONTH%-%CURRENTDATETIME_DAY% %CURRENTDATETIME_HOUR%:%CURRENTDATETIME_MINUTE%:%CURRENTDATETIME_SECOND%.%CURRENTDATETIME_MILLISECOND%

IF /I "%~1" == "/X" (
    ECHO.CURRENTDATETIME=%CURRENTDATETIME%
    ECHO.
    ECHO.YEAR=%CURRENTDATETIME_YEAR%
    ECHO.MONTH=%CURRENTDATETIME_MONTH%
    ECHO.DAY=%CURRENTDATETIME_DAY%
    ECHO.HOUR=%CURRENTDATETIME_HOUR%
    ECHO.MINUTE=%CURRENTDATETIME_MINUTE%
    ECHO.SECOND=%CURRENTDATETIME_SECOND%
    ECHO.MILLISECOND=%CURRENTDATETIME_MILLISECOND%
)
