@ECHO OFF

FOR /F "tokens=1-3 delims=/ " %%a IN ('DATE /t') DO (
    SET CURRENTDATETIME_YEAR=%%c
    SET CURRENTDATETIME_MONTH=%%b
    SET CURRENTDATETIME_DAY=%%a
)

FOR /F "tokens=1-2 delims=/:" %%a IN ('TIME /t') DO (
    SET CURRENTDATETIME_HOUR=%%a
    SET CURRENTDATETIME_MINUTE=%%b
    SET CURRENTDATETIME_SECOND=00
    SET CURRENTDATETIME_MILLISECOND=000
)

SET CURRENTDATETIME=%CURRENTDATETIME_YEAR%-%CURRENTDATETIME_MONTH%-%CURRENTDATETIME_DAY% %CURRENTDATETIME_HOUR%:%CURRENTDATETIME_MINUTE%:%CURRENTDATETIME_SECOND%.%CURRENTDATETIME_MILLISECOND%

IF /I "%~1" == "/X" (
    ECHO.Current Date/Time : [%CURRENTDATETIME%]
    
    ECHO.YEAR=%CURRENTDATETIME_YEAR%
    ECHO.MONTH=%CURRENTDATETIME_MONTH%
    ECHO.DAY=%CURRENTDATETIME_DAY%
    ECHO.HOUR=%CURRENTDATETIME_HOUR%
    ECHO.MINUTE=%CURRENTDATETIME_MINUTE%
    ECHO.SECOND=%CURRENTDATETIME_SECOND%
    ECHO.MILLISECOND=%CURRENTDATETIME_MILLISECOND%
)
