@ECHO OFF

SETLOCAL EnableDelayedExpansion

SET SCRIPTPATH=%~dp0
SET SCRIPTNAME=%~n0
SET SCRIPTFULLFILENAME=%~dpnx0

FOR %%* IN (.) DO SET CURRENTDIR=%%~dpn*
FOR %%* IN (.) DO SET CURRENTDIRNAME=%%~n*

SET REPO_CONFIG_FILENAME=.git.config.toml

SET DEBUG=N
SET DRYRUN=N
SET HELP=N
SET ARGPOS=0
SET COMMAND=
SET COMMANDARGS=

SET COMMANDPREFIX=

SET SHOWCOMMAND=N

SET COMMANDCOUNT=0
SET COMMANDALIASCOUNT=0

REM                 NAME    LABEL               DESCRIPTION
CALL :DEFINECOMMAND clone   CLONE               "Clone a Repo"
CALL :DEFINECOMMAND baseurl BASEURL             "Set the Base URL for repos in this folder"
CALL :DEFINECOMMAND status  STATUS              "Show current status information"
CALL :DEFINECOMMAND branch  BRANCH              "Show current branch"
CALL :DEFINECOMMAND unstage UNSTAGE             "Unstage a file already added"
CALL :DEFINECOMMAND reset   RESET               "Reset (Undo) changes to a file"
CALL :DEFINECOMMAND remstat REMOTEBRANCHSTATUS  "Show Remote Branch Status"
CALL :DEFINECOMMAND config  SHOWCONFIG          "Show all Config (with scopes / files)"
CALL :DEFINECOMMAND clean   CLEAN               "Clean all untracked files" 

CALL :DEFINECOMMANDALIAS cfg config

SET MAXCOMMANDNAMEDISPLAYLENGTH=8

:PARSE
IF "%~1" === "" GOTO :VALIDATE
IF /I "%~1" == "/?"  SET HELP=Y&&SHIFT&&GOTO :PARSE
IF /I "%~1" == "-?"  SET HELP=Y&&SHIFT&&GOTO :PARSE
IF /I "%~1" == "/X"  SET DEBUG=Y&&SHIFT&&GOTO :PARSE
IF /I "%~1" == "-X"  SET DEBUG=Y&&SHIFT&&GOTO :PARSE
IF /I "%~1" == "/Z"  SET DRYRUN=Y&&SHIFT&&GOTO :PARSE
IF /I "%~1" == "-Z"  SET DRYRUN=Y&&SHIFT&&GOTO :PARSE

IF /I "%~1" == "/SC" SET SHOWCOMMAND=Y&&SHIFT&&GOTO :PARSE
IF /I "%~1" == "-SC" SET SHOWCOMMAND=Y&&SHIFT&&GOTO :PARSE


SET /A ARGPOS+=1
IF %ARGPOS% EQU 1 SET COMMAND=%~1&& SHIFT && GOTO :PARSE


:VALIDATE
IF "%HELP%" == "Y" CALL :USAGE && GOTO :EOF
IF "%DEBUG%" == "Y" SET SHOWCOMMAND=Y
IF "%DRYRUN%" == "Y" SET COMMANDPREFIX=@ECHO.

REM *** Match a command
SET FOUND=

CALL :LOCATECOMMANDEXACT "%COMMAND%"
IF NOT "%FOUND%" == "" (
    CALL :EXECUTE_!LABEL! %*
    GOTO :EOF
)

CALL :LOCATECOMMANDBEST "%COMMAND%"
IF NOT "%FOUND%" == "" (
    CALL :EXECUTE_!LABEL! %*
    GOTO :EOF
)

ECHO.
ECHO.Error: Command not found: %COMMAND%

IF %CANDIDATES% GTR 0 (
    ECHO.
    ECHO.Ambiguous Command:
    FOR /L %%F IN (1,1,%CANDIDATES%) DO (
        CALL :SETCOMMANDBYINDEX !CANDIDATE[%%F]!

        ECHO.!NAME! - !DESC!
    )
)

GOTO :EOF


:DEFINECOMMAND

SET /A COMMANDCOUNT+=1
SET COMMAND[%COMMANDCOUNT%].NAME=%~1
SET COMMAND[%COMMANDCOUNT%].LABEL=%~2
SET COMMAND[%COMMANDCOUNT%].DESC=%~3

GOTO :EOF


:DEFINECOMMANDALIAS

SET /A COMMANDALIASCOUNT+=1
SET COMMANDALIAS[%COMMANDALIASCOUNT%].ALIAS=%~1
SET COMMANDALIAS[%COMMANDALIASCOUNT%].NAME=%~2

GOTO :EOF


:ERROR
ECHO.Error: %*

GOTO :EOF


:WARNING
ECHO.Warning: %*

GOTO :EOF


:SETCOMMANDBYINDEX
SET NAME=!COMMAND[%~1].NAME!
SET LABEL=!COMMAND[%~1].LABEL!
SET DESC=!COMMAND[%~1].DESC!

GOTO :EOF


:LOCATECOMMANDEXACT
SET FOUND=

FOR /L %%F IN (1,1,%COMMANDCOUNT%) DO (
    CALL :SETCOMMANDBYINDEX %%F
    
    IF /I "%~1" == "!NAME!" (
        SET FOUND=%%F
        GOTO :EOF
    )
)

GOTO :EOF


:LOCATECOMMANDBEST
SET FOUND=

SET CANDIDATES=0

FOR /L %%F IN (1,1,%COMMANDCOUNT%) DO (
    CALL :SETCOMMANDBYINDEX %%F
    
    ECHO.!NAME!|FINDSTR "^%~1">NUL && SET /A CANDIDATES+=1 && SET "CANDIDATE[!CANDIDATES!]=%%F"
)

IF %CANDIDATES% EQU 0 (
    GOTO :EOF
)

IF %CANDIDATES% EQU 1 (
    SET FOUND=%CANDIDATE[1]%
    CALL :SETCOMMANDBYINDEX %CANDIDATE[1]%
    GOTO :EOF
)

GOTO :EOF


:USAGE
ECHO.%SCRIPTNAME% - GIT shortcuts
ECHO.
ECHO.Usage: %SCRIPTNAME% [options] <command> [args]
ECHO.Commands
FOR /L %%F IN (1,1,%COMMANDCOUNT%) DO (
    CALL :SETCOMMANDBYINDEX %%F

    REM ECHO.!NAME! - !DESC!
    REM PRINTFORMAT   "{0,-%MAXCOMMANDNAMEDISPLAYLENGTH%} - {1}" "!NAME!" "!DESC!"
    PRINTFORMAT_R "{:<%MAXCOMMANDNAMEDISPLAYLENGTH%} - {}" "!NAME!" "!DESC!"
)
ECHO.
ECHO.Options:
ECHO./?             - Show Usage
ECHO./X             - Activate Debug mode (Default: %DEBUG%)
ECHO./Z             - Activate Dry Run mode (Default: %DRYRUN%)
ECHO./SC            - Show Commands (Default: %SHOWCOMMAND%)

GOTO :EOF


:EXECUTE_CLONE
CALL GetTOMLValue.cmd ".BaseUrl" -f %REPO_CONFIG_FILENAME%

SET SOURCE=%~2
IF /I "%SOURCE:~1,7%" == "http://" (
    ECHO.Using source : %SOURCE%
) ELSE IF /I "%SOURCE:~1,8%" == "https://" (
    ECHO.Using source : %SOURCE%
) ELSE (
    SET SOURCE=%TOMLVALUE%%SOURCE%
    ECHO.Using source %TOMLVALUE%%SOURCE%
)

@IF "%SHOWCOMMAND%" == "Y" @ECHO ON
%COMMANDPREFIX%git clone %SOURCE%
@IF "%SHOWCOMMAND%" == "Y" @ECHO OFF
GOTO :EOF


:EXECUTE_BASEURL
IF "%~2" == "" (
    CALL :ERROR Invalid Base URL
    GOTO :EOF
)

ECHO.BaseUrl = %~2> %REPO_CONFIG_FILENAME%
TYPE %REPO_CONFIG_FILENAME%

GOTO :EOF


:EXECUTE_STATUS
@IF "%SHOWCOMMAND%" == "Y" @ECHO ON
%COMMANDPREFIX%git status
@IF "%SHOWCOMMAND%" == "Y" @ECHO OFF

GOTO :EOF


:EXECUTE_BRANCH
@IF "%SHOWCOMMAND%" == "Y" @ECHO ON
%COMMANDPREFIX%git rev-parse --abbrev-ref HEAD
@IF "%SHOWCOMMAND%" == "Y" @ECHO OFF

GOTO :EOF


:EXECUTE_UNSTAGE
IF "%~2" == "" (
  CALL :ERROR Invalid filename to unstage
  GOTO :EOF
)

@IF "%SHOWCOMMAND%" == "Y" @ECHO ON
%COMMANDPREFIX%git reset HEAD "%~2"
@IF "%SHOWCOMMAND%" == "Y" @ECHO OFF

GOTO :EOF


:EXECUTE_RESET
IF "%~2" == "" (
  CALL :ERROR Invalid filename to reset
  GOTO :EOF
)

@IF "%SHOWCOMMAND%" == "Y" @ECHO ON
%COMMANDPREFIX%git checkout -- "%~2"
@IF "%SHOWCOMMAND%" == "Y" @ECHO OFF

GOTO :EOF


:EXECUTE_REMOTEBRANCHSTATUS
CALL BUILDUNIQUETEMPFILENAME "%SCRIPTNAME%.RemoteBranchStatus.tmp"
SET TEMPFILENAME=%UNIQUETEMPFILENAME%

@IF "%SHOWCOMMAND%" == "Y" @ECHO ON
%COMMANDPREFIX%git branch -r | grep -v HEAD > "%TEMPFILENAME%"
@IF "%SHOWCOMMAND%" == "Y" @ECHO OFF

FOR /F %%F IN (%TEMPFILENAME%) DO CALL :SHOWSTATUS "%%~F"

DEL /Q "%TEMPFILENAME%" >NUL

GOTO :EOF


:EXECUTE_SHOWSTATUS
@IF "%SHOWCOMMAND%" == "Y" @ECHO ON
%COMMANDPREFIX%git show --format="%%ci %%cr %%cn %%d" "%~1" | head -n 1
@IF "%SHOWCOMMAND%" == "Y" @ECHO OFF

GOTO :EOF


:EXECUTE_SHOWCONFIG
SET PARAM=--show-scope
IF /I "%~2" == "FILE"  SET PARAM=--show-origin
IF /I "%~2" == "FILES" SET PARAM=--show-origin

@IF "%SHOWCOMMAND%" == "Y" @ECHO ON
%COMMANDPREFIX%git config --list %PARAM%
@IF "%SHOWCOMMAND%" == "Y" @ECHO OFF

GOTO :EOF


:EXECUTE_CLEAN
REM https://stackoverflow.com/questions/61212/how-do-i-remove-local-untracked-files-from-the-current-git-working-tree

@IF "%SHOWCOMMAND%" == "Y" @ECHO ON
%COMMANDPREFIX%git clean -fdx
@IF "%SHOWCOMMAND%" == "Y" @ECHO OFF

GOTO :EOF
