@ECHO OFF

SETLOCAL

SET SCRIPTPATH=%~dp0
SET SCRIPTNAME=%~n0
SET SCRIPTFULLFILENAME=%~dpnx0

SET COMMANDEXTENSIONS=*.cmd *.bat *.ps1
SET EXECUTABLEEXTENSIONS=*.exe *.com
SET EXTENSIONS=%EXECUTABLEEXTENSIONS% %COMMANDEXTENSIONS%
SET RECURSE=

:PARSEARGS
IF /I "%~1" == "/S" (
    SET RECURSE=/S
    SHIFT
    GOTO :PARSEARGS
)

IF NOT "%~1" == "" (
    SET MYFOLDER=%~1
    SHIFT
    GOTO :PARSEARGS
)

:SETDEFAULTS
IF "%MYFOLDER%" == "" (
    FOR %%* IN (.) DO SET MYFOLDER=%%~dpnx*
)
IF "%MYFOLDER%" == "" (
    FOR %%* IN (.) DO SET MYFOLDER=%%~dp*
)

SET DESCRIPTION=%MYFOLDER%
IF NOT "%RECURSE%" == "" SET DESCRIPTION=%DESCRIPTION% (and subfolders)

:GO
BANNERTEXT -hlc "=" -flc "=" -tlc "=" -tsc 0 "Commands for: %DESCRIPTION%"
ECHO.

SET REPLACE=%MYFOLDER:\=\\%
if "%MYFOLDER%" == "." SET REPLACE=
if "%MYFOLDER%" == ".." SET REPLACE=

PUSHD "%MYFOLDER%"

DIR %RECURSE% %EXTENSIONS% /B 2>&1 | SED -e "s/^%REPLACE%//g" -e "s/^\\//g" | SED -e "s/^File Not Found$/No commands found/g"

POPD
