@ECHO OFF

IF "%~1" == "" (
    ECHO.Available Functions:
    ECHO.
    FINDSTR "^:[^_]" %~dpnx0 | SORT
    GOTO :EOF
)
SET LABEL=
FOR /F %%C IN ('grep -E -i "^:%~1([ ]+.*)*$" %~dpnx0') DO SET LABEL=%%C
IF "%LABEL%" == "" (
   CALL :ERROR "Unknown command: %~1"
   GOTO :EOF
)

SET ARGS=
:_BUILD_ARGS
IF "%~2" == "" GOTO :_GO

SET ARGS=%ARGS% "%~2"
SHIFT /2
GOTO :_BUILD_ARGS

:_GO
CALL %LABEL% %ARGS%
GOTO :EOF


:SETUP {FullScriptPathName} {Description}
IF "%~1" == "" CALL :ERROR "SETUP - missing argument at position 1 - FullScriptPathName" && GOTO :EOF
IF "%~2" == "" CALL :ERROR "SETUP - missing argument at position 2 - Description" && GOTO :EOF

SET SCRIPTNAME=%~n1
SET SCRIPTPATH=%~dp1
SET SCRIPTFULLFILENAME=%~dpnx1
SET SCRIPTDESCRIPTION=%~2

SET HELP=N
SET DEBUG=N
SET DRYRUN=N
SET VERBOSE=N

SET ARGPOS=0
SET ALLOWEDOPTIONFLAGPREFIXCOUNT=0
SET KNOWNOPTIONCOUNT=0
SET KNOWNFLAGCOUNT=0
SET KNOWNCOMMANDCOUNT=0
SET KNOWNALIASCOUNT=0
SET COMMANDCOUNT=0
SET DEFAULTOPTIONFLAGPREFIX=

SET ALLOWMULTICOMMANDEXECUTION=N

REM TODO: Calculate these dynamically
SET MAXCOMMANDNAMEDISPLAYLENGTH=20
SET MAXOPTIONNAMEDISPLAYLENGTH=20

GOTO :EOF


:PARSEARGUMENT
SET PARSEDCOUNT=0

CALL :_PARSEKNOWNFLAG "%~1"
IF "%FOUND%" == "Y" (
    SET PARSEDCOUNT=1
    GOTO :EOF
)








REM TODO


GOTO :EOF


:_PARSEKNOWNFLAG
SET FOUND=N

SET INDEX=0
FOR /L %%P IN (1,1,%ALLOWEDOPTIONFLAGPREFIXCOUNT%) DO (
    FOR /L %%I IN (1,1,%KNOWNFLAGCOUNT%) DO (
        IF /I "%~1" == "%ALLOWEDOPTIONFLAGPREFIX[%%P]%%KNOWNFLAG[%%I].NAME%" (
             SET INDEX=%%I
             SET FOUND=Y
            IF "%KNOWNFLAG[%%I].ALLOWDISABLE%" == "Y" (
                IF /I "%~2" == "/%KNOWNFLAG[%%I].NAME%-" (
                    SET FOUND=Y
                    CALL :_SETFLAGVALUE %~1 OFF
                    GOTO :EOF
                )
            )
            CALL :_SETFLAGVALUE %~1 ON
            GOTO :EOF
        )
    )
    


    IF /I "%~1" == "%ALLOWEDOPTIONFLAGPREFIX[%%P]%%~2" (
        SET FOUND=Y
        GOTO :EOF
    )
)

GOTO :EOF


:DEFINESTANDARDOPTIONSANDFLAGS
CALL :DEFINEALLOWEDOPTIONFLAGPREFIXES "-" "/"

REM                   NAME      SW  DESCRIPTION                                             ALLOW DISABLE VIA - SUFFIX
CALL :DEFINEKNOWNFLAG HELP      ?   "Show Usage" 
CALL :DEFINEKNOWNFLAG DEBUG     X   "Activate Debug Mode (Default: %DEBUG%)"
CALL :DEFINEKNOWNFLAG DRYRUN    Z   "Activate DryRun Mode (Default: %DRYRUN%)"
CALL :DEFINEKNOWNFLAG VERBOSE   V   "Enable/Disable Verbose Output (Default: %VERBOSE%)"    Y

GOTO :EOF


:DEFINEALLOWEDOPTIONFLAGPREFIXES
IF "%~1" == "" GOTO :EOF

SET ALLOWEDOPTIONFLAGPREFIXCOUNT=0

:_DEFINEALLOWEDOPTIONFLAGPREFIXES_PARSE
IF "%~1" == "" GOTO :EOF

SET /A ALLOWEDOPTIONFLAGPREFIXCOUNT+=1
SET ALLOWEDOPTIONFLAGPREFIX[%ALLOWEDOPTIONFLAGPREFIXCOUNT%]=%~1
SHIFT
GOTO :_DEFINEALLOWEDOPTIONFLAGPREFIX_PARSE


:DEFINEALLOWEDOPTIONFLAGPREFIX
IF "%~1" == "" GOTO :EOF

SET /A ALLOWEDOPTIONFLAGPREFIXCOUNT+=1
SET ALLOWEDOPTIONFLAGPREFIX[%ALLOWEDOPTIONFLAGPREFIXCOUNT%]=%~1

IF %~1 EQU 1 SET DEFAULTOPTIONFLAGPREFIX=%~1

GOTO :EOF


:DEFINEKNOWNOPTION
IF "%~1" == "" GOTO :EOF
IF "%~2" == "" GOTO :EOF
IF "%~3" == "" GOTO :EOF

SET /A KNOWNOPTIONCOUNT+=1
SET KNOWNOPTION[%KNOWNOPTIONCOUNT%].NAME=%~1
SET KNOWNOPTION[%KNOWNOPTIONCOUNT%].PARAMETER=%~2
SET KNOWNOPTION[%KNOWNOPTIONCOUNT%].DESC=%~3

GOTO :EOF


:DEFINEKNOWNFLAG
IF "%~1" == "" GOTO :EOF
IF "%~2" == "" GOTO :EOF
IF "%~3" == "" GOTO :EOF

SET /A KNOWNFLAGCOUNT+=1
SET KNOWNFLAG[%KNOWNFLAGCOUNT%].NAME=%~1
SET KNOWNFLAG[%KNOWNFLAGCOUNT%].PARAMETER=%~2
SET KNOWNFLAG[%KNOWNFLAGCOUNT%].DESC=%~3
SET KNOWNFLAG[%KNOWNFLAGCOUNT%].ALLOWDISABLE=%~4

GOTO :EOF


:DEFINEKNOWNCOMMAND
IF "%~1" == "" GOTO :EOF
IF "%~2" == "" GOTO :EOF
IF "%~3" == "" GOTO :EOF

SET /A KNOWNCOMMANDCOUNT+=1
SET KNOWNCOMMAND[%KNOWNCOMMANDCOUNT%].NAME=%~1
SET KNOWNCOMMAND[%KNOWNCOMMANDCOUNT%].LABEL=%~2
SET KNOWNCOMMAND[%KNOWNCOMMANDCOUNT%].DESC=%~3

GOTO :EOF


:DEFINEKNOWNALIAS
IF "%~1" == "" GOTO :EOF
IF "%~2" == "" GOTO :EOF

SET /A KNOWNALIASCOUNT+=1
SET KNOWNALIAS[%KNOWNALIASCOUNT%].ALIAS=%~1
SET KNOWNALIAS[%KNOWNALIASCOUNT%].NAME=%~2

GOTO :EOF


:SHOWUSAGE
SET LINE=Usage: %SCRIPTNAME%
IF %KNOWNCOMMANDCOUNT% GTR 0 SET LINE=%LINE% [command]
IF %KNOWNOPTIONCOUNT% GTR 0 SET LINE=%LINE% [options]
IF %KNOWNFLAGCOUNT% GTR 0  SET LINE=%LINE% [flags]
IF NOT "%SCRIPTDESCRIPTION%" == "" SET LINE=%LINE% - %SCRIPTDESCRIPTION%
ECHO.%LINE%

IF %KNOWNCOMMANDCOUNT% GTR 0 (
    ECHO.
    ECHO.Commands:
    FOR /L %%I IN (1,1,%KNOWNCOMMANDCOUNT%) DO CALL :_SHOWCOMMANDUSAGE %%I
)

SET /A OPTIONFLAGCOUNT=%KNOWNOPTIONCOUNT% + %KNOWNFLAGCOUNT%

IF %OPTIONFLAGCOUNT% GTR 0 (
    ECHO.
    ECHO.Options:
)

IF %KNOWNOPTIONCOUNT% GTR 0 (
    FOR /L %%I IN (1,1,%KNOWNOPTIONCOUNT%) DO CALL :_SHOWOPTIONUSAGE %%I
)

IF %KNOWNFLAGCOUNT% GTR 0 (
    FOR /L %%I IN (1,1,%KNOWNFLAGCOUNT%) DO CALL :_SHOWFLAGUSAGE %%I
)

GOTO :EOF


:DEBUG
IF NOT "%DEBUG%" == "Y" GOTO :EOF
ECHO.DEBUG: %*
GOTO :EOF


:_SHOWCOMMANDUSAGE
IF "%~1" == "" GOTO :EOF
PRINTFORMAT_R -t C "%%-%MAXCOMMANDNAMEDISPLAYLENGTH%s %%s" "!KNOWNCOMMAND[%~1].NAME!" "!KNOWNCOMMAND[%~1].DESC!"
GOTO :EOF


:_SHOWOPTIONUSAGE
IF "%~1" == "" GOTO :EOF
PRINTFORMAT_R -t C "%%-%MAXOPTIONNAMEDISPLAYLENGTH%s %%s" "!KNOWNOPTION[%~1].NAME!" "!KNOWNOPTION[%~1].DESC!"
GOTO :EOF


:ERROR
SET ERRORTEXT=
:_ERRORLOOP
IF NOT "%~1" == "" (
  SET ERRORTEXT=%ERRORTEXT% %~1
  SHIFT
  GOTO :_ERRORLOOP
)
ECHO.ERROR:%ERRORTEXT%
GOTO :EOF


:WARNING
SET WARNINGTEXT=
:_WARNINGLOOP
IF NOT "%~1" == "" (
  SET WARNINGTEXT=%WARNINGTEXT% %~1
  SHIFT
  GOTO :_WARNINGLOOP
)
ECHO.WARNING:%WARNINGTEXT%
GOTO :EOF
