@ECHO OFF

SETLOCAL

SET SCRIPTPATH=%~dp0
SET SCRIPTNAME=%~n0
SET SCRIPTFULLFILENAME=%~dpnx0

SET APPFOLDER=C:\ProgramData\NuGet
SET APPBASENAME=nuget
SET APPEXTENSION=exe

:VERSIONDETECT
CALL "%SCRIPTPATH%\GetTOMLValue.cmd" ".version" -f "%APPFOLDER%\version.toml"
SET APPVERSION=%TOMLVALUE%

CALL "%SCRIPTPATH%\GetTOMLValue.cmd" ".version" -f "version.toml"
IF NOT "%TOMLVALUE%" == "" SET APPVERSION=%TOMLVALUE%


:PARSE
IF /I "%~1" == "/L" GOTO :LIST
IF /I "%~1" == "-L" GOTO :LIST


:EXECUTE
SET APPEXE=%APPFOLDER%\%APPBASENAME%_%APPVERSION%.%APPEXTENSION%

%APPEXE% %*

GOTO :EOF


:LIST
ECHO.%SCRIPTNAME% available versions (Default: %APPVERSION%)
ECHO.
DIR /b "%APPFOLDER%\*.%APPEXTENSION%" | SED -e "s/%APPBASENAME%_/v/g" -e "s/.%APPEXTENSION%//g"

GOTO :EOF
