@ECHO OFF

SETLOCAL EnableDelayedExpansion

SET PATHS=%PATH%
SET INDEX=0

SET SHOWEMPTY=Y

:PARSEOPTS
IF /I "%~1" == "/E" SET SHOWEMPTY=Y&&SHIFT && GOTO :PARSEOPTS
IF /I "%~1" == "-E" SET SHOWEMPTY=Y&&SHIFT && GOTO :PARSEOPTS
IF /I "%~1" == "/E-" SET SHOWEMPTY=N&&SHIFT && GOTO :PARSEOPTS
IF /I "%~1" == "-E-" SET SHOWEMPTY=N&&SHIFT && GOTO :PARSEOPTS

:GO
FOR %%A IN ("%PATHS:;=";"%") DO (
  CALL :SHOWPATH %%A
)

GOTO :EOF


:SHOWPATH
IF "%~1" == "" (
  IF "%SHOWEMPTY%" == "N" GOTO :EOF
)

SET TEXT= %~1
IF NOT EXIST "%~1\*.*" SET TEXT=*%~1

SET /A INDEX += 1

SET ID=%INDEX%
IF %ID% LSS 10 SET ID= %ID%

ECHO.%ID%:%TEXT%

GOTO :EOF
