@ECHO OFF

SETLOCAL EnableDelayedExpansion

SET PATHS=%PATH%
SET INDEX=0

SET SHOWEMPTY=Y
SET SHOWSUMMARY=Y

:PARSEOPTS
IF /I "%~1" == "/E"  SET SHOWEMPTY=Y&&SHIFT && GOTO :PARSEOPTS
IF /I "%~1" == "-E"  SET SHOWEMPTY=Y&&SHIFT && GOTO :PARSEOPTS
IF /I "%~1" == "/E-" SET SHOWEMPTY=N&&SHIFT && GOTO :PARSEOPTS
IF /I "%~1" == "-E-" SET SHOWEMPTY=N&&SHIFT && GOTO :PARSEOPTS
IF /I "%~1" == "/S"  SET SHOWSUMMARY=Y&&SHIFT && GOTO :PARSEOPTS
IF /I "%~1" == "-S"  SET SHOWSUMMARY=Y&&SHIFT && GOTO :PARSEOPTS
IF /I "%~1" == "/S-" SET SHOWSUMMARY=N&&SHIFT && GOTO :PARSEOPTS
IF /I "%~1" == "-S-" SET SHOWSUMMARY=N&&SHIFT && GOTO :PARSEOPTS

:GO
SET TOTALCOUNT=0
SET EMPTYCOUNT=0
SET NOTFOUNDCOUNT=0

FOR %%A IN ("%PATHS:;=";"%") DO (
  CALL :SHOWPATH %%A
)

IF "%SHOWSUMMARY%" == "Y" (
  ECHO.
  ECHO.Total: %TOTALCOUNT%
  IF %EMPTYCOUNT% GTR 0 ECHO.Empty Paths: %EMPTYCOUNT%
  IF %NOTFOUNDCOUNT% GTR 0 ECHO.Not Found: %NOTFOUNDCOUNT%
)

GOTO :EOF


:SHOWPATH
IF "%~1" == "" (
  IF "%SHOWEMPTY%" == "N" GOTO :EOF
  SET /A EMPTYCOUNT += 1
)

SET /A TOTALCOUNT += 1

SET TEXT= %~1
IF NOT EXIST "%~1\*.*" SET TEXT=*%~1
IF NOT EXIST "%~1\*.*" SET /A NOTFOUNDCOUNT += 1

SET /A INDEX += 1

SET ID=%INDEX%
IF %ID% LSS 10 SET ID= %ID%

ECHO.%ID%:%TEXT%

GOTO :EOF
