@ECHO OFF

SETLOCAL EnableDelayedExpansion

SET SCRIPTPATH=%~dp0
SET SCRIPTNAME=%~n0
SET SCRIPTFULLFILENAME=%~dpnx0

IF "%~1" == "" (
  CALL :USAGE
  GOTO :EOF
)

SET WWWADDRESS=%~1
SET WWWHTTP=%WWWADDRESS:~0,5%
SET WWWHTTPS=%WWWADDRESS:~0,6%

IF /I "%WWWHTTP%"  == "HTTP:"  GOTO DOIT
IF /I "%WWWHTTPS%" == "HTTPS:" GOTO DOIT

SET WWWADDRESS=http://%WWWADDRESS%

:DOIT
START "%~1" "%WWWADDRESS%"

GOTO :EOF


:USAGE
ECHO.%SCRIPTNAME% - Launch a web page in the default browser
ECHO.
ECHO.Usage:
ECHO.%SCRIPTNAME% "web address"

GOTO :EOF
