@ECHO OFF

SETLOCAL EnableDelayedExpansion

SET APPNAME=KeepAlive
SET APPDESCRIPTION=Keep Windows alive
SET APPFILENAME=%APPNAME%.ahk
SET EXEFILENAME=%APPNAME%.exe
SET ICONFILENAME=%APPNAME%.ico

CALL ..\BuildAHK.cmd "%~n0" "%APPNAME%" "%APPDESCRIPTION%" "%APPFILENAME%" "%EXEFILENAME%" "%ICONFILENAME%"
