@ECHO OFF

SETLOCAL EnableDelayedExpansion

SET APPNAME=DirMenu
SET APPDESCRIPTION=Directory Menu
SET APPFILENAME=%APPNAME%.ahk
SET EXEFILENAME=%APPNAME%.exe
SET ICONFILENAME=Hopstarter-Mac-Folders-2-Folder-Download.ico

CALL ..\BuildAHK.cmd "%~n0" "%APPNAME%" "%APPDESCRIPTION%" "%APPFILENAME%" "%EXEFILENAME%" "%ICONFILENAME%"
