@ECHO OFF

SETLOCAL EnableDelayedExpansion

PUSHD "%dp0"

SET APPNAME=ClickFix
SET APPDESCRIPTION=Mouse ClickFix
SET APPFILENAME=%APPNAME%.ahk
SET EXEFILENAME=%APPNAME%.exe
SET ICONFILENAME=icon\ClickFix-icon.ico

CALL ..\BuildAHK.cmd "%~n0" "%APPNAME%" "%APPDESCRIPTION%" "%APPFILENAME%" "%EXEFILENAME%" "%ICONFILENAME%"

POPD
